name: CI
on:
  push:
    branches:
      - master

jobs: 
  build_android:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run : flutter pub get
      - run : flutter build apk --debug
      
  build_ios:
    name: Build and Release Ios
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.0'
    - run : flutter pub get
    - run: |
        flutter build ios --no-codesign
        cd build/ios/iphoneos
        mkdir Payload
        cd Payload
        ln -s ../Runner.app
        cd ..
        zip -r app.ipa Payload
  

  push_to_releases:
    name: push to release
    runs-on: macos-latest
    needs: [build_android,build_ios]
    steps:
    - name : Push to Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }}
    
    
